version: '3.1'

services:
  api:
    build: .
    image: suspicious-api
    ports:
      - 3000:8080
    environment:
      - JWT_SECRET=${JWT_SECRET}
      - PORT=${PORT}
      - DB_NAME=${DB_NAME}
      - DB_ADDRESS=${DB_ADDRESS}
      - DB_USER=${DB_USER}
      - DB_PWD=${DB_PWD}
      - DB_URI=${DB_URI}
    volumes:
      - .:/usr/app/
